### ISSUE TITLE
Missing documentation on adding custom plugins

### ISSUE THREAD

**Issue by meetandrey** [kubic-project/health-checker#18]
Hey folks! I tried to figure out how to create a custom plugin for health checker, but didn't find any instructions. The closest thing is **Chapter 3.1** from **SLE Micro Administration Guide**. This document basically says that you need two parts, a plugin, and modified health-checker.service file.

This chapter is named **Adding custom plugins**. There is a mention to place custom plugins to `/usr/libexec/health-checker` directory, but the entire `/usr` is ready-only!

Can anybody please advise, how to actually create a health checker plugin, MicroOS-way?

**Comment by thkukuk** [comment]
https://manpages.opensuse.org/health-checker describes the plugin and directories, where you can store them.

If you want to add something to the read-only `/usr` part: This is generic SLE Micro system management, so please read the chapter about this (see `transactional-update`). Best is still to create an own RPM and install that.
