### ISSUE TITLE
clearing grub flag doesn't work on transactional server

### ISSUE THREAD

**Issue by fcrozat** [kubic-project/health-checker#4]
From logs:

health-checker[1762]: Clearing GRUB flag
health-checker[1762]: grub2-editenv : error: can't open " /boot/grub2/gruben" : Read-only filesystem

**Comment by laenion** [comment]
It does work, it just prints that error message; the `health_checker_flag` variable is stored in the Btrfs header, so setting the variable there does work.

See https://bugzilla.opensuse.org/show_bug.cgi?id=1126900 for the current discussion on how to get rid of the message and adding the possibility to store non-special variables.

**Comment by thkukuk** [comment]
Closing, see last comment.
