### ISSUE TITLE
Breaks bootloader if multiple menuentries present

### ISSUE THREAD

**Issue by Vogtinator** [kubic-project/health-checker#5]
If there are multiple `menuentry` to be emitted into `grub.cfg`, the hack in `/etc/grub.d/83_health_check_marker` breaks, which results in a corrupted configuration file.

This can be fixed by replacing the ugly hack with a much nicer one:

```
 # Reopen the now changed output file in append mode
 exec >> "$cfgfile"
```

**Comment by Vogtinator** [comment]
Turns out the "much nicer hack" doesn't fully work either. I assumed that the scripts inside `grub.d` were  sourced, but that's not the case, so they only share already opened file descriptors.

I'll try to find an equivalent of `python3 -c 'import os; os.lseek(1, 0, os.SEEK_END)'`.

**Comment by Vogtinator** [comment]
This seems to work fine:

`dd oflag=append count=0 status=none`

It does

```
[pid  1146] fcntl(1, F_GETFL)           = 0x8001 (flags O_WRONLY|O_LARGEFILE)
[pid  1146] fcntl(1, F_SETFL, O_WRONLY|O_APPEND|O_LARGEFILE) = 0
```

so forces the `O_APPEND` flag to stdout. This is not quite the same as seeking to the end of the replaced file content, but forces that every write to stdout ends up appended. That's arguably much better.

**Comment by laenion** [comment]
Using to `dd` to set `O_APPEND` now as suggested.
